Enable linux

diff --git a/scripts/install-deps b/scripts/install-deps
--- a/scripts/install-deps
+++ b/scripts/install-deps
@@ -1,11 +1,19 @@
 #!/usr/bin/env bash
 set -e
 
-if ! hash brew 2>/dev/null; then
-  echo "✖ Homebrew not found. Please install: https://brew.sh/"
-  exit 1
-else
-  echo "✓ Found homebrew"
+unameOut="$(uname -s)"
+case "${unameOut}" in
+  Darwin*)    machine=mac;;
+  *)          machine=linux
+esac
+
+if [ "$machine" == "mac" ]; then
+  if ! hash brew 2>/dev/null; then
+    echo "✖ Homebrew not found. Please install: https://brew.sh/"
+    exit 1
+  else
+    echo "✓ Found homebrew"
+  fi
 fi
 
 if ! hash dotnet 2>/dev/null; then
@@ -13,9 +21,15 @@ if ! hash dotnet 2>/dev/null; then
   echo
   if [[ $REPLY =~ ^[Yy]$ ]]
   then
-    curl -o /tmp/dotnet.pkg https://download.visualstudio.microsoft.com/download/pr/4850aa8f-44a9-4c4a-9961-f18aa4d90ceb/07d790444f3ba6b412a76d6f1aced338/dotnet-sdk-2.2.105-osx-x64.pkg
-    echo "Installing dotnet requires sudo..."
-    sudo installer -pkg /tmp/dotnet.pkg -target /
+    if [ "$machine" == "mac" ]; then
+      curl -o /tmp/dotnet.pkg https://download.visualstudio.microsoft.com/download/pr/4850aa8f-44a9-4c4a-9961-f18aa4d90ceb/07d790444f3ba6b412a76d6f1aced338/dotnet-sdk-2.2.105-osx-x64.pkg
+      echo "Installing dotnet requires sudo..."
+      sudo installer -pkg /tmp/dotnet.pkg -target /
+    else
+      sudo apt-get install apt-transport-https
+      sudo apt-get update
+      sudo apt-get install dotnet-sdk-2.2
+    fi
     echo "✓ Installed dotnet"
   else
     exit 1
